In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.pyplot as plta

print(mpl.__version__)   # shows version of matplotlib

import numpy as np

3.7.5


In [2]:

data_df =  pd.read_csv("Advertising.csv")

In [3]:
data_df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [4]:
X = data_df[['TV','radio']].to_numpy()
Y = data_df[['sales']].to_numpy()


In [5]:
X = np.concatenate((np.ones((200,1)), X), axis=1)


In [6]:
beats = np.linalg.inv(np.dot(X.T,X)).dot(X.T).dot(Y)

In [7]:
beats

array([[2.92109991],
       [0.04575482],
       [0.18799423]])

In [8]:
print(f"y={beats[0].item():.3f}+{beats[1].item():.3f}*x1+{beats[2].item():.3f}*x2")


y=2.921+0.046*x1+0.188*x2


### sklearn implementation

In [9]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=909)


In [11]:

linear_reg = LinearRegression()
linear_reg.fit(X_train,y_train)

LinearRegression()

In [12]:

linear_reg.coef_

array([[0.        , 0.04593985, 0.18832644]])

In [13]:
linear_reg.intercept_

array([2.8900462])

In [16]:
from sklearn.metrics import r2_score

In [17]:
y_pred = linear_reg.predict(X_test)


In [18]:
r2_score(y_test,y_pred)

0.9322324795473396