In [2]:
import numpy as np

In [10]:
a = np.random.randint(10,50,size=(5,2,3))

In [11]:
a

array([[[31, 17, 13],
        [27, 14, 32]],

       [[19, 32, 10],
        [14, 30, 38]],

       [[44, 16, 44],
        [31, 48, 42]],

       [[45, 41, 30],
        [19, 27, 45]],

       [[42, 15, 12],
        [34, 39, 15]]])

In [12]:
a.shape

(5, 2, 3)

In [13]:
a.ndim

3

In [14]:
a.dtype

dtype('int32')

In [15]:
a.size

30

In [16]:
a.T

array([[[31, 19, 44, 45, 42],
        [27, 14, 31, 19, 34]],

       [[17, 32, 16, 41, 15],
        [14, 30, 48, 27, 39]],

       [[13, 10, 44, 30, 12],
        [32, 38, 42, 45, 15]]])

In [17]:
a.reshape(10,3)

array([[31, 17, 13],
       [27, 14, 32],
       [19, 32, 10],
       [14, 30, 38],
       [44, 16, 44],
       [31, 48, 42],
       [45, 41, 30],
       [19, 27, 45],
       [42, 15, 12],
       [34, 39, 15]])

In [20]:
a.ravel()

array([31, 17, 13, 27, 14, 32, 19, 32, 10, 14, 30, 38, 44, 16, 44, 31, 48,
       42, 45, 41, 30, 19, 27, 45, 42, 15, 12, 34, 39, 15])

In [21]:
a

array([[[31, 17, 13],
        [27, 14, 32]],

       [[19, 32, 10],
        [14, 30, 38]],

       [[44, 16, 44],
        [31, 48, 42]],

       [[45, 41, 30],
        [19, 27, 45]],

       [[42, 15, 12],
        [34, 39, 15]]])

In [39]:
b = np.random.randint(1,10,size=(2,3))
c = np.random.randint(1,10,size=(2,3))

In [40]:
b

array([[2, 4, 6],
       [2, 3, 4]])

In [41]:
c

array([[1, 8, 3],
       [4, 3, 2]])

In [42]:
d = np.concatenate([b,c],axis = 0)
d

array([[2, 4, 6],
       [2, 3, 4],
       [1, 8, 3],
       [4, 3, 2]])

### 0 > column wise >vstack
### 1 >row wise >hstack

In [49]:

np.split(d,2,axis=0)


[array([[2, 4, 6],
        [2, 3, 4]]),
 array([[1, 8, 3],
        [4, 3, 2]])]

In [9]:
m = np.random.randint(1,10,size=(4,6))

In [10]:
m

array([[8, 7, 4, 4, 7, 2],
       [3, 1, 2, 8, 6, 4],
       [8, 2, 3, 9, 5, 2],
       [4, 8, 3, 5, 4, 8]])

In [11]:
m.sum(axis = 1)

array([32, 24, 29, 32])

In [12]:
m.prod(axis = 0)


array([ 768,  112,   72, 1440,  840,  128])

In [13]:
m.cumsum()

array([  8,  15,  19,  23,  30,  32,  35,  36,  38,  46,  52,  56,  64,
        66,  69,  78,  83,  85,  89,  97, 100, 105, 109, 117])

In [14]:
m.max(axis=1)

array([8, 8, 9, 8])

In [15]:
m.min(axis = 0)

array([3, 1, 2, 4, 4, 2])

In [16]:

m.argmax()

15

In [17]:
m.max()

9

In [18]:
m.clip(5,10)

array([[8, 7, 5, 5, 7, 5],
       [5, 5, 5, 8, 6, 5],
       [8, 5, 5, 9, 5, 5],
       [5, 8, 5, 5, 5, 8]])