In [1]:
import numpy as np

In [22]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[3,2,1],[9,8,1]])

In [23]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[3, 2, 1],
        [9, 8, 1]]))


# arithmetic operation 

In [24]:
#a+b
np.add(a,b)

array([[ 7,  7,  7],
       [14, 15, 10]])

In [25]:
#a-b
np.subtract(a,b)

array([[ 1,  3,  5],
       [-4, -1,  8]])

In [26]:
#a*b
np.multiply(a,b)

array([[12, 10,  6],
       [45, 56,  9]])

In [27]:
#a**2
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 81]], dtype=int32)

In [28]:
#a %b
np.divmod(a,b)

(array([[1, 2, 6],
        [0, 0, 9]]),
 array([[1, 1, 0],
        [5, 7, 0]]))

In [29]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

In [30]:
np.floor(b)

array([[3., 2., 1.],
       [9., 8., 1.]])

In [31]:
np.ceil(a)

array([[4., 5., 6.],
       [5., 7., 9.]])

In [32]:
new= 1/np.tan(b)
new

array([[-7.01525255, -0.45765755,  0.64209262],
       [-2.21084541, -0.14706506,  0.64209262]])

### rounding operations


In [34]:
np.round(new,decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])

### matrix operations

In [2]:
a = np.array([[4,5,6],[1,2,3]])
b = np.random.randint(0,10,(3,3))

In [3]:
a


array([[4, 5, 6],
       [1, 2, 3]])

In [4]:
b

array([[3, 2, 4],
       [2, 6, 7],
       [2, 8, 0]])

In [5]:
np.dot(a,b)

array([[34, 86, 51],
       [13, 38, 18]])

In [6]:
a.T

array([[4, 1],
       [5, 2],
       [6, 3]])

In [7]:
np.transpose(a)

array([[4, 1],
       [5, 2],
       [6, 3]])

In [9]:
np.trace(a)

6

# inverse

In [11]:
np.linalg.det(b)

-124.00000000000003

In [14]:
np.linalg.inv(b)

array([[ 0.4516129 , -0.25806452,  0.08064516],
       [-0.11290323,  0.06451613,  0.10483871],
       [-0.03225806,  0.16129032, -0.11290323]])

In [15]:
np.dot(
    b,np.linalg.inv(b)
).round()

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [-0., -0.,  1.]])

### solve eqn

x+2y = 1 ,3x+5y = 2

In [22]:
a = np.array([[1,2],[3,5]])
b = np.array([1,2])

In [23]:
# x = np.dot(b,np.linalg.inv(a))

x = np.linalg.solve(a,b)

In [24]:
x

array([-1.,  1.])

In [25]:
np.dot(a,x)

array([1., 2.])

### array broadcasting

In [27]:
a * np.array([2,3])

array([[ 2,  6],
       [ 6, 15]])