In [1]:
import numpy as np

In [22]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[3,2,1],[9,8,1]])

In [23]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[3, 2, 1],
        [9, 8, 1]]))


# arithmetic operation 

In [24]:
#a+b
np.add(a,b)

array([[ 7,  7,  7],
       [14, 15, 10]])

In [25]:
#a-b
np.subtract(a,b)

array([[ 1,  3,  5],
       [-4, -1,  8]])

In [26]:
#a*b
np.multiply(a,b)

array([[12, 10,  6],
       [45, 56,  9]])

In [27]:
#a**2
np.power(a,2)

array([[16, 25, 36],
       [25, 49, 81]], dtype=int32)

In [28]:
#a %b
np.divmod(a,b)

(array([[1, 2, 6],
        [0, 0, 9]]),
 array([[1, 1, 0],
        [5, 7, 0]]))

In [29]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

In [30]:
np.floor(b)

array([[3., 2., 1.],
       [9., 8., 1.]])

In [31]:
np.ceil(a)

array([[4., 5., 6.],
       [5., 7., 9.]])

In [32]:
new= 1/np.tan(b)
new

array([[-7.01525255, -0.45765755,  0.64209262],
       [-2.21084541, -0.14706506,  0.64209262]])

### rounding operations


In [34]:
np.round(new,decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])