In [1]:
import numpy as np

In [4]:
np.__version__

'1.24.4'

### creating array

In [5]:
list1 = [2,3,4]


In [6]:
arr1 = np.array(list1)

In [7]:
arr1

array([2, 3, 4])

In [8]:
arr1.shape

(3,)

In [9]:
arr1.ndim

1

In [12]:
list2 = [[2,3,4],
         [5,6,7],
         [8,9,1]]
arr2 = np.array(list2)

In [13]:
arr2

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [14]:
arr2.shape

(3, 3)

In [15]:
arr2.ndim

2

In [16]:
arr2

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [18]:
np.zeros(shape = (4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((2,2) , dtype = "int8")

array([[1, 1],
       [1, 1]], dtype=int8)

In [22]:
np.full((3,4),6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [29]:
np.random.randint(0,10,(2,2))

array([[7, 1],
       [4, 5]])

# accessing array`

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a[-3]

3

In [4]:
a[0:4:2]

array([1, 3])

In [7]:
a[::-1]


array([5, 4, 3, 2, 1])

In [8]:
#2d

In [11]:
n = np.random.randint(0,10,size=(3,3))

In [12]:
n

array([[1, 2, 8],
       [0, 3, 4],
       [7, 5, 8]])

In [13]:
n[1,1]

3

In [14]:
n[1,2]

4

In [15]:
n[-1,0]

7

### slicing 2d array

In [18]:
n[1:3,:2]   #aagadi ko row pachi column

array([[0, 3],
       [7, 5]])

In [19]:
n[:,2]

array([8, 4, 8])

### slicing 3d array

In [20]:
c = np.random.randint(0,10,size=(3,3,2))

In [21]:
c


array([[[7, 2],
        [4, 6],
        [5, 3]],

       [[3, 3],
        [3, 1],
        [6, 5]],

       [[7, 8],
        [3, 6],
        [2, 0]]])

In [22]:
c[0]

array([[7, 2],
       [4, 6],
       [5, 3]])

In [25]:
c[0,2,1]

3

In [27]:
c[:,2,:]

array([[5, 3],
       [6, 5],
       [2, 0]])

# boolean or mask indexing

In [38]:
b= np.random.randint(1,10,(5,5))

In [43]:
b

array([[6, 4, 7, 7, 3],
       [5, 4, 9, 4, 7],
       [8, 2, 2, 5, 4],
       [9, 9, 1, 3, 8],
       [5, 4, 8, 5, 6]])

In [44]:
mask = b > 5

In [45]:
mask

array([[ True, False,  True,  True, False],
       [False, False,  True, False,  True],
       [ True, False, False, False, False],
       [ True,  True, False, False,  True],
       [False, False,  True, False,  True]])

In [46]:
b[mask]

array([6, 7, 7, 9, 7, 8, 9, 9, 8, 8, 6])