In [1]:
import numpy as np

In [4]:
np.__version__

'1.24.4'

### creating array

In [5]:
list1 = [2,3,4]


In [6]:
arr1 = np.array(list1)

In [7]:
arr1

array([2, 3, 4])

In [8]:
arr1.shape

(3,)

In [9]:
arr1.ndim

1

In [12]:
list2 = [[2,3,4],
         [5,6,7],
         [8,9,1]]
arr2 = np.array(list2)

In [13]:
arr2

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [14]:
arr2.shape

(3, 3)

In [15]:
arr2.ndim

2

In [16]:
arr2

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [18]:
np.zeros(shape = (4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((2,2) , dtype = "int8")

array([[1, 1],
       [1, 1]], dtype=int8)

In [22]:
np.full((3,4),6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [28]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [29]:
np.random.randint(0,10,(2,2))

array([[7, 1],
       [4, 5]])